// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQNAEpKeS22WFKgbx848HXdcGG8L_Df94',
    appId: '1:699181975672:web:2fa890006ecd95385b458d',
    messagingSenderId: '699181975672',
    projectId: 'nutrisee-b8c92',
    authDomain: 'nutrisee-b8c92.firebaseapp.com',
    storageBucket: 'nutrisee-b8c92.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkxNDkbJ8t4DI2Qa3tOvOwaLvEOLjUGXs',
    appId: '1:699181975672:android:6ff14922494c63575b458d',
    messagingSenderId: '699181975672',
    projectId: 'nutrisee-b8c92',
    storageBucket: 'nutrisee-b8c92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRuD8CL2dxjwiVfojT0RaTvM8y_oYm-P8',
    appId: '1:699181975672:ios:555c49fcf6cc71435b458d',
    messagingSenderId: '699181975672',
    projectId: 'nutrisee-b8c92',
    storageBucket: 'nutrisee-b8c92.appspot.com',
    iosBundleId: 'com.example.nutrisee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRuD8CL2dxjwiVfojT0RaTvM8y_oYm-P8',
    appId: '1:699181975672:ios:d9cccde8929398625b458d',
    messagingSenderId: '699181975672',
    projectId: 'nutrisee-b8c92',
    storageBucket: 'nutrisee-b8c92.appspot.com',
    iosBundleId: 'com.example.nutrisee.RunnerTests',
  );
}
